# Generated by Django 3.1.14 on 2023-05-23 22:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='文章标题')),
                ('body', models.TextField(verbose_name='文章内容')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='文章创建时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='文章更新时间')),
                ('total_views', models.PositiveIntegerField(default=0)),
                ('article_type', models.CharField(choices=[('Kubernetes', 'Kubernetes'), ('Go', 'Go'), ('Python', 'Python'), ('Linux', 'Linux'), ('中间件', '中间件'), ('前端', '前端'), ('数据库', '数据库'), ('其他', '其他')], max_length=20, verbose_name='文章类型')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '博客文章',
                'verbose_name_plural': '博客文章',
            },
        ),
    ]
